name: TaskApp CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------------- Backend ----------------
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Build backend
        working-directory: ./backend
        run: mvn clean install -DskipTests

      - name: Run backend tests
        working-directory: ./backend
        run: mvn test

      # ---------------- Frontend ----------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Selenium tests
        working-directory: ./frontend
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          npm run test:selenium
